Add ability to generate enums with Q_ENUM macros
cornelius/libkode pull request #32
Opened 2021-01-27 10:51 UTC by martonmiklos

The enum declarations are indented to newlines. 
The enum class now generates the declarations through a Code object (which ease the indentation handling).
The Enum::declaration does not used elsewhere so we might remove that. KDSoap and KODE does not use it directly only through the Printer, which got modified in this commit to use the new Code object based approach.

2021-01-27 11:21 UTC, martonmiklos commented
@dfaure-kdab 

I think enums could be present in the kdwsdl2cpp generated codes, and this change will make the enums with lot items looks nicer, so I would appreciate a review ;)

2021-01-28 08:55 UTC, martonmiklos commented
@dfaure-kdab thanks for the review, I have fixed the highlighted issues.
One thing came into my mind: it would be useful to remove the QString Enum::declaration, since it was only used in the Printer which is now using the printDeclaration.

2021-01-28 09:03 UTC, dfaure-kdab requested changes
Yes, you could remove declaration() in a separate commit.

2021-01-28 09:03 UTC, dfaure-kdab commented on code_generation/enum.h
> +     * (The later got set automatically if a signal or slot declaration to the class.)
The latter

2021-01-28 09:37 UTC, merged